package com.dappley.java.core.po;

import lombok.Data;

/**
 * Data returned by send transaction request
 */
@Data
public class SendTxResult {
    /**
     * Request status
     */
    private boolean isSuccess;
    /**
     * Contract address generated by new transaction
     */
    private String generatedContractAddress;
}
