package com.dappley.java.core.po;

import lombok.Data;

/**
 * Data returned by send transaction request
 */
@Data
public class SendTxResult {
    /**
     * Success
     */
    public static final int CODE_SUCCESS = 0;
    /**
     * Exception caused error
     */
    public static final int CODE_ERROR_EXCEPTION = -1;
    /**
     * Params error
     */
    public static final int CODE_ERROR_PARAM = -2;
    /**
     * Balance is not enough
     */
    public static final int CODE_ERROR_BALANCE = -3;
    /**
     * Request status
     */
    private int code;
    /**
     * Error message
     */
    private String msg;
    /**
     * Contract address generated by new transaction
     */
    private String generatedContractAddress;
}
